import type { Category, InformationItem } from "@/types";

const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_CATEGORIES: Category[] = [
  { id: "cat-sungalt", name: "Сунгалттай холбоотой", slug: "sungalt", color: "#f6a06b", icon: "RefreshCw", display_order: 1, is_active: true, created_at: daysAgo(120), updated_at: daysAgo(120) },
  { id: "cat-dans", name: "Данс, цэнэглэлт", slug: "dans", color: "#aebf92", icon: "Wallet", display_order: 2, is_active: true, created_at: daysAgo(120), updated_at: daysAgo(120) },
  { id: "cat-admin", name: "Админ дугаарын бүртгэл", slug: "admin", color: "#c0b6a5", icon: "UserCog", display_order: 3, is_active: true, created_at: daysAgo(120), updated_at: daysAgo(120) },
  { id: "cat-kino", name: "Кино ба контент", slug: "kino", color: "#d67f48", icon: "Film", display_order: 4, is_active: true, created_at: daysAgo(120), updated_at: daysAgo(120) },
  { id: "cat-kollektiv", name: "Коллектив үйлчилгээ", slug: "kollektiv", color: "#8fa073", icon: "Users", display_order: 5, is_active: true, created_at: daysAgo(120), updated_at: daysAgo(120) },
  { id: "cat-upoint", name: "Upoint үйлчилгээ", slug: "upoint", color: "#ffc6a5", icon: "Star", display_order: 6, is_active: true, created_at: daysAgo(120), updated_at: daysAgo(120) },
  { id: "cat-ger", name: "Гэр дүүрэн үйлчилгээ", slug: "ger", color: "#ccdbb2", icon: "Home", display_order: 7, is_active: true, created_at: daysAgo(120), updated_at: daysAgo(120) },
  { id: "cat-zalruulga", name: "Алдаатай гүйлгээ залруулах", slug: "zalruulga", color: "#b2622d", icon: "RotateCcw", display_order: 8, is_active: true, created_at: daysAgo(120), updated_at: daysAgo(120) },
  { id: "cat-noat", name: "НӨАТ бүртгэл", slug: "noat", color: "#a19786", icon: "Receipt", display_order: 9, is_active: true, created_at: daysAgo(120), updated_at: daysAgo(120) },
  { id: "cat-busad", name: "Идэвхжүүлэлт ба бусад", slug: "busad", color: "#dcd3c4", icon: "CircleEllipsis", display_order: 10, is_active: true, created_at: daysAgo(120), updated_at: daysAgo(120) },
];

export const MOCK_ITEMS: InformationItem[] = [
  {
    id: "item-i1",
    category_id: "cat-admin",
    title: "Админ дугаараа солих",
    message: "Shinechleh zai awaad shineer burtguuleh utasni dugaaraa bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 1,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(29),
    updated_at: daysAgo(1),
  },
  {
    id: "item-i2",
    category_id: "cat-admin",
    title: "Админ бүртгэлээс устгах бол",
    message: "USTGAH gej bicheed 139898 dugaart ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 2,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(28),
    updated_at: daysAgo(2),
  },
  {
    id: "item-i3",
    category_id: "cat-admin",
    title: "Нууц код авах",
    message: "KOD gej bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: "хэрэглэгч ярьж дуусаад ая яваад таслаагүй тул таслав",
    keywords: null,
    display_order: 3,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(27),
    updated_at: daysAgo(3),
  },
  {
    id: "item-i4",
    category_id: "cat-admin",
    title: "Нууц код солих",
    message: "Solih zai awaad shine nuuts kod bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: "хэрэглэгч ярьж дуусаад таслаагүй тул таслав",
    keywords: null,
    display_order: 4,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(26),
    updated_at: daysAgo(4),
  },
  {
    id: "item-i5",
    category_id: "cat-admin",
    title: "Гишүүн харах",
    message: "Admin dugaaraasaa HARAH gej bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 5,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(25),
    updated_at: daysAgo(0),
  },
  {
    id: "item-i6",
    category_id: "cat-admin",
    title: "Гишүүн дугаараа хасах",
    message: "Admin dugaaraasaa -******** /hasah gej bui dugaar/-aa bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 6,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(24),
    updated_at: daysAgo(1),
  },
  {
    id: "item-i7",
    category_id: "cat-admin",
    title: "Гишүүн дугаараа нэмэх",
    message: "Admin dugaaraasaa +******** /nemeh gej bui dugaar/-aa bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 7,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(23),
    updated_at: daysAgo(2),
  },
  {
    id: "item-i8",
    category_id: "cat-noat",
    title: "НӨАТ бүртгүүлэх",
    message: "Admin dugaaraasaa T zai awaad E-barimtiin 8 orontoi kodoo bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 8,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(22),
    updated_at: daysAgo(3),
  },
  {
    id: "item-i9",
    category_id: "cat-noat",
    title: "НӨАТ-ийн бүртгэлээ солих",
    message: "Admin dugaaraasaa T zai awaad Solih zai awaad E-barimtiin 8 orontoi kodoo bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 9,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(21),
    updated_at: daysAgo(4),
  },
  {
    id: "item-i10",
    category_id: "cat-kino",
    title: "NVOD кино захиалахад",
    message: "800 zai awaad kinoni kodoo bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: "Админ болон гишүүн дугаараас",
    keywords: null,
    display_order: 10,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(20),
    updated_at: daysAgo(0),
  },
  {
    id: "item-i11",
    category_id: "cat-kino",
    title: "RVOD кино захиалахад",
    message: "Kino sangaas zahilahdaa KINO zai awaad kinoni kodoo bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: "Админ болон гишүүн дугаараас",
    keywords: null,
    display_order: 11,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(19),
    updated_at: daysAgo(1),
  },
  {
    id: "item-i12",
    category_id: "cat-kino",
    title: "Админ дугаараасаа хөтөлбөр харах",
    message: "Suvgiin dugaar zai awaad hutulbur gej bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: "Дурын дугаараас шалгаж болно",
    keywords: null,
    display_order: 12,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(18),
    updated_at: daysAgo(2),
  },
  {
    id: "item-i13",
    category_id: "cat-kino",
    title: "Зурагтнаасаа сувагийн хөтөлбөр харах",
    message: "Suvagan deeree taviad udirdlaganii EPG tovchiig daraad harah bolomjtoi.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 13,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(17),
    updated_at: daysAgo(3),
  },
  {
    id: "item-i14",
    category_id: "cat-kino",
    title: "Дансны үлдэгдэл шалгах",
    message: "Dans gej bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 14,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(16),
    updated_at: daysAgo(4),
  },
  {
    id: "item-i15",
    category_id: "cat-sungalt",
    title: "Үндсэн багц сунгалт хийх заавар",
    message: "Khan dans -76 000 500 5059050128\nhuleen awagch - DDISHTV\nmongon dun - 40000\nguilgeni utga - admin dugaraa biched zai awad L1 gej bicheed hiine uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 15,
    is_popular: true,
    is_active: true,
    created_at: daysAgo(15),
    updated_at: daysAgo(0),
  },
  {
    id: "item-i16",
    category_id: "cat-sungalt",
    title: "Лизин картны сунгалт",
    message: "Khan dans - 76 000 500 5059050128\nhuleen awagch - DDISHTV\nmongon dun - 35000\nguilgeni utga - admin dugaraa biched zai awad M1 gej bicheed hiine uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 16,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(14),
    updated_at: daysAgo(1),
  },
  {
    id: "item-i17",
    category_id: "cat-sungalt",
    title: "Нэмэлт багц сунгалт",
    message: "Khan dans -76 000 500 5059050128\nhuleen awagch - DDISHTV\nmongon dun - 10000\nguilgeni utga - admin dugaraa biched zai awad C1 gej bicheed hiine uu.\nDDISH",
    additional_info: "Khan dans -76 000 500 5059050128\nhuleen awagch - DDISHTV\nmongon dun - 10000\nguilgeni utga - admin dugaraa biched zai awad K1 gej bicheed hiine uu.\nDDISH",
    keywords: null,
    display_order: 17,
    is_popular: true,
    is_active: true,
    created_at: daysAgo(13),
    updated_at: daysAgo(2),
  },
  {
    id: "item-i18",
    category_id: "cat-sungalt",
    title: "6 сарын лизин төлбөр",
    message: "Khan dans - 76 000 500 5059050128\nhuleen awagch - DDISHTV\nmongon dun - 60000\nguilgeni utga - admin dugaraa biched zai awad TULBUR gej bicheed hiine uu.\nDDISH",
    additional_info: "Khan dans -76 000 500 5059050128\nhuleen awagch - DDISHTV\nmongon dun - 50000\nguilgeni utga - admin dugaraa biched zai awad TULBUR gej bicheed hiine uu.\nDDISH",
    keywords: null,
    display_order: 18,
    is_popular: true,
    is_active: true,
    created_at: daysAgo(12),
    updated_at: daysAgo(3),
  },
  {
    id: "item-i19",
    category_id: "cat-sungalt",
    title: "Khanbank internet bank",
    message: "Tulbur-Busad tulbur-Kabeliin tolbor- DDISH-ru orj sungaltaa hiine uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 19,
    is_popular: true,
    is_active: true,
    created_at: daysAgo(11),
    updated_at: daysAgo(4),
  },
  {
    id: "item-i20",
    category_id: "cat-sungalt",
    title: "Toki application",
    message: "TV, Internet-Ddishtv-admin eswel kartni dugaaraa bicheed-bagtsaa songood-sungaltaa hiine uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 20,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(30),
    updated_at: daysAgo(0),
  },
  {
    id: "item-i21",
    category_id: "cat-sungalt",
    title: "Хоногийн зээлийн үйлчилгээ авах",
    message: "Admin dugaaraasaa Zeel gej bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: "Сунгалт дууссан өдрөөс 3 хоногийн дотор 24 цагийн зээл авах боломжтой.",
    keywords: null,
    display_order: 21,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(29),
    updated_at: daysAgo(1),
  },
  {
    id: "item-i22",
    category_id: "cat-dans",
    title: "Дансны дугаар авах мөн виртуал данс цэнэглэх заавар авахдаа",
    message: "Zaavar gej bicheed 139898-d ilgeegeed sungalt hiih dansnii dugaaruud awah bolomjtoi.\nDDISH",
    additional_info: "Khan bank:76 000 500 5059050128 - DDISHTV\nTuriin bank: 26 00 34 106600004668 - DDISHTV\nGolomt bank: 2300 1500 1102987935 - DDISHTV\nKhas bank dans- 3700 3200 5000232657 - DDISHTV\nTDB- 52 000 4000 499135803 huleen awagch - DDISHTV",
    keywords: null,
    display_order: 22,
    is_popular: true,
    is_active: true,
    created_at: daysAgo(28),
    updated_at: daysAgo(2),
  },
  {
    id: "item-i23",
    category_id: "cat-dans",
    title: "Банкны үйлчилгээ ашиглан ДАНС цэнэглэх",
    message: "Tulbur-Busad tulbur-Kabeliin tolbor- DDISH-Dans tsenegleh-ru orj dansaa tseneglene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 23,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(27),
    updated_at: daysAgo(3),
  },
  {
    id: "item-i24",
    category_id: "cat-dans",
    title: "Төгс картаар ДАНС цэнэглэх заавар",
    message: "Negjni 12 oron buhii kodiig bichin zai awaad smart kartin buh dugaariig bichin 139898-d ilgeene uu.\nDDISH",
    additional_info: "Дурын юнител дугаараас мсж илгээж болно",
    keywords: null,
    display_order: 24,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(26),
    updated_at: daysAgo(4),
  },
  {
    id: "item-i25",
    category_id: "cat-dans",
    title: "Нэгжийн бэлэг үйлчилгээ ашиглан ДАНС цэнэглэх",
    message: "Tseneglelt hiih smart kartiin dugaariin buh orong bicheed zai avaad tsenegleh\nmungun dungee bicheed 1444 ruu ilgeene uu.\nDDISH",
    additional_info: "1000, 1500, 2000, 3000, 5000, 6000, 8000, 10'000, 15'000, 20'000, 25'000 байна. Сард цэнэглэх нэгжийн дээд хязгаар: 50,000төг",
    keywords: null,
    display_order: 25,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(25),
    updated_at: daysAgo(0),
  },
  {
    id: "item-i26",
    category_id: "cat-zalruulga",
    title: "Мөнгөн дүнгээ буцаан авах хүсэлт илгээхэд",
    message: "call@ddishtv.mn haygaar mungu tushaasan bankni tamgatai barimt, kart ezemshigchiin bichig barimtni huulbar, garaar bichsen huseltee ilgeene uu.\nDDISH",
    additional_info: "Facebook-Ddish\nБанкны баримтны аль нэг зайнд зөв картын дугаар бичих, хүсэлтээ дэлгэрэнгүй илгээх заавар өгнө.",
    keywords: null,
    display_order: 26,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(24),
    updated_at: daysAgo(1),
  },
  {
    id: "item-i27",
    category_id: "cat-zalruulga",
    title: "Смарт картаа сунгуулах залруулга мейлээр илгээхэд",
    message: "call@ddishtv.mn haygaar mungu tushaasan bankni tamgatai barimt, kart ezemshigchiin bichig barimtni huulbar, garaar bichsen huseltee ilgeene uu.\nDDISH",
    additional_info: "mail- call@ddishtv.mn",
    keywords: null,
    display_order: 27,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(23),
    updated_at: daysAgo(2),
  },
  {
    id: "item-i28",
    category_id: "cat-zalruulga",
    title: "Смарт картаа сунгуулах залруулга фейсбүүк чатаар илгээхэд",
    message: "DDISH page chataar mungu tushaasan bankni tamgatai barimt, kart ezemshigchiin bichig barimtni huulbar, garaar bichsen huseltee ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 28,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(22),
    updated_at: daysAgo(3),
  },
  {
    id: "item-i29",
    category_id: "cat-zalruulga",
    title: "Төгс картын залруулга хийхдээ",
    message: "Ta negjnii husaj arilgasan heseg bolon DDISH smart kartiin zurag, garaar bichsen huseltee DDISH chat esvel call@ddishtv.mn haygaar ilgeen zasuulah bolomjtoi.",
    additional_info: null,
    keywords: null,
    display_order: 29,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(21),
    updated_at: daysAgo(4),
  },
  {
    id: "item-i30",
    category_id: "cat-ger",
    title: "Гэр дүүрэн сунгалт хийх заавар",
    message: "Haan dans - 503 803 5092\nhuleen awagch - UNITEL\nmungun dun - *****\nguilgeni utga - ger internet-n dugaaraa bicheed hiine uu.",
    additional_info: "Khan bank: 503 803 5092\nTuriin bank: 1060 0002 4579\nGolomt bank: 8115 006 438\nHHbank: 490009704\nKhas bank dans 5000 420 765",
    keywords: null,
    display_order: 30,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(20),
    updated_at: daysAgo(0),
  },
  {
    id: "item-i31",
    category_id: "cat-ger",
    title: "Гэр дүүрэн төлбөр шалгах",
    message: "Admin dugaaraasaa Tulbur gej bicheed 1401/131401 dugaart ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 31,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(19),
    updated_at: daysAgo(1),
  },
  {
    id: "item-i32",
    category_id: "cat-ger",
    title: "NVOD сувгаас кино захиалахад",
    message: "800 zai awaad kinoni kodoo bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 32,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(18),
    updated_at: daysAgo(2),
  },
  {
    id: "item-i33",
    category_id: "cat-ger",
    title: "RVOD сувгаас кино захиалахад",
    message: "Ta zuvhun kinoni kodoo bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: "Ta 801.802.803 suwgaa sungahdaa K gej bicheed 139898dugaart ilgeene uu.\nDDISH",
    keywords: null,
    display_order: 33,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(17),
    updated_at: daysAgo(3),
  },
  {
    id: "item-i34",
    category_id: "cat-busad",
    title: "Happy family — Unitel family tur salgah zaawar",
    message: "Off zai awaad Unitel gej bicheed 139898 dugaart ilgeene uu.\nDDISH",
    additional_info: "haah",
    keywords: null,
    display_order: 34,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(16),
    updated_at: daysAgo(4),
  },
  {
    id: "item-i35",
    category_id: "cat-busad",
    title: "Happy family — Neeh zaawar",
    message: "ON zai awaad Unitel gej bicheed 139898 dugaart ilgeene uu.\nDDISH",
    additional_info: "neeh",
    keywords: null,
    display_order: 35,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(15),
    updated_at: daysAgo(0),
  },
  {
    id: "item-i36",
    category_id: "cat-sungalt",
    title: "Админаар Standart багц сунгах заавар",
    message: "Admin dugaaraasaa S zai awaad 1 gej bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 36,
    is_popular: true,
    is_active: true,
    created_at: daysAgo(14),
    updated_at: daysAgo(1),
  },
  {
    id: "item-i37",
    category_id: "cat-sungalt",
    title: "Админаар Happy багц сунгах заавар",
    message: "Admin dugaaraasaa M zai awaad 1 gej bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 37,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(13),
    updated_at: daysAgo(2),
  },
  {
    id: "item-i38",
    category_id: "cat-sungalt",
    title: "Админаар Super багц сунгах заавар",
    message: "Admin dugaaraasaa L zai awaaad 1 gej bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 38,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(12),
    updated_at: daysAgo(3),
  },
  {
    id: "item-i39",
    category_id: "cat-sungalt",
    title: "6 сарын лизинг төлөх заавар",
    message: "Admin dugaaraasaa TULBUR zai awaad 1 gej bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 39,
    is_popular: true,
    is_active: true,
    created_at: daysAgo(11),
    updated_at: daysAgo(4),
  },
  {
    id: "item-i40",
    category_id: "cat-sungalt",
    title: "Фанат багц",
    message: "Admin dugaaraasaa C zai awaad 1 gej bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 40,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(30),
    updated_at: daysAgo(0),
  },
  {
    id: "item-i41",
    category_id: "cat-sungalt",
    title: "Киночин багц",
    message: "Admin dugaaraasaa K zai awaad 1 gej bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 41,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(29),
    updated_at: daysAgo(1),
  },
  {
    id: "item-i42",
    category_id: "cat-sungalt",
    title: "Standart-s Happy руу багц ахиулах заавар",
    message: "Admin dugarasa ahiulah bagtsiin kod M gej bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 42,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(28),
    updated_at: daysAgo(2),
  },
  {
    id: "item-i43",
    category_id: "cat-sungalt",
    title: "Happy-s Super багц руу багц ахиулах заавар",
    message: "Admin dugarasa ahiulah bagtsiin kod L gej bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 43,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(27),
    updated_at: daysAgo(3),
  },
  {
    id: "item-i44",
    category_id: "cat-kino",
    title: "Live 900 тоглолт захиалах заавар",
    message: "Admin dugaaraasaa 900 zai awaad kontentiin kodoo bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: "Банкаар шууд захиалах заавар",
    keywords: null,
    display_order: 44,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(26),
    updated_at: daysAgo(4),
  },
  {
    id: "item-i45",
    category_id: "cat-kino",
    title: "899 суваг",
    message: "Admin dugaaraasaa 899 zai awaad kontentiin kodoo bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: "Khan dans - 505 905 0128\nhuleen awagch - DDISHTV\nmongon dun -10000\nguilgeni utga-admin dugaraa biched zai awad 900 zai awad 13 gej bicheed hiine uu.\nDDISH",
    keywords: null,
    display_order: 45,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(25),
    updated_at: daysAgo(0),
  },
  {
    id: "item-i46",
    category_id: "cat-kino",
    title: "Playboy сунгах",
    message: "Admin dugaaraasaa 41 zai awaad 1 gej bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 46,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(24),
    updated_at: daysAgo(1),
  },
  {
    id: "item-i47",
    category_id: "cat-kino",
    title: "Суваг нээж, хаах",
    message: "Admin dugaaraasaa 901 zai awaad ON gej bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 47,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(23),
    updated_at: daysAgo(2),
  },
  {
    id: "item-i48",
    category_id: "cat-kino",
    title: "Суваг нээж, хаах",
    message: "Admin dugaaraasaa 901 zai awaad OFF gej bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 48,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(22),
    updated_at: daysAgo(3),
  },
  {
    id: "item-i49",
    category_id: "cat-kino",
    title: "NVOD сувгаас кино бүртгэлтэй дугаараас үзэх бол",
    message: "Ta admin dugaaraasaa NEGJ zai awaad 800 zai awaad kinonii kodoo bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 49,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(21),
    updated_at: daysAgo(4),
  },
  {
    id: "item-i50",
    category_id: "cat-kino",
    title: "NVOD сувгаас кино бүртгэлгүй дугаараас үзэх бол",
    message: "Ta NEGJ zai awaad 800 zai awaad kinonii kod zai awaad smart kartiin buh orong bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 50,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(20),
    updated_at: daysAgo(0),
  },
  {
    id: "item-i51",
    category_id: "cat-kino",
    title: "RVOD сувгаас кино бүртгэлтэй дугаараас үзэх бол",
    message: "Ta admin dugaaraasaa NEGJ zai awaad KINO zai awaad kinonii kodoo bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 51,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(19),
    updated_at: daysAgo(1),
  },
  {
    id: "item-i52",
    category_id: "cat-kino",
    title: "RVOD сувгаас кино бүртгэлгүй дугаараас үзэх бол",
    message: "Ta NEGJ zai awaad KINO zai awaad kinonii kod zai awaad smart kartiin buh orong bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 52,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(18),
    updated_at: daysAgo(2),
  },
  {
    id: "item-i53",
    category_id: "cat-kino",
    title: "900 LIVE бүртгэлтэй дугаараас үзэх бол",
    message: "Ta Admin dugaaraasaa NEGJ zai awaad 900 zai awaad kontentin kodoo bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 53,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(17),
    updated_at: daysAgo(3),
  },
  {
    id: "item-i54",
    category_id: "cat-kino",
    title: "900 LIVE бүртгэлгүй дугаараас үзэх бол",
    message: "Ta NEGJ zai awaad 900 zai awaad kontentin kodoo bicheed zai awaad smart kartiin buh orong bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 54,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(16),
    updated_at: daysAgo(4),
  },
  {
    id: "item-i55",
    category_id: "cat-kollektiv",
    title: "Коллектив карт холбох",
    message: "Nemeh temdeg /+/ smartiin kartiin dugaaraa bicheed 1415-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 55,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(15),
    updated_at: daysAgo(0),
  },
  {
    id: "item-i56",
    category_id: "cat-kollektiv",
    title: "Коллектив гишүүн нэмэх",
    message: "Nemeh zai awaad utasnii dugaar bicheed 4422 -d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 56,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(14),
    updated_at: daysAgo(1),
  },
  {
    id: "item-i57",
    category_id: "cat-kollektiv",
    title: "Коллектив гишүүн хасах",
    message: "Hasah zai awaad utasnii dugaar bicheed 4422 -d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 57,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(13),
    updated_at: daysAgo(2),
  },
  {
    id: "item-i58",
    category_id: "cat-kollektiv",
    title: "Коллектив админаас гишүүн устгах",
    message: "Delete gej bicheed 4422 -d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 58,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(12),
    updated_at: daysAgo(3),
  },
  {
    id: "item-i59",
    category_id: "cat-kollektiv",
    title: "Коллектив админ болон гишүүн дугаар харах",
    message: "Gishuun gej bicheed 4422 -d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 59,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(11),
    updated_at: daysAgo(4),
  },
  {
    id: "item-i60",
    category_id: "cat-upoint",
    title: "Upoint-д бүртгүүлэх",
    message: "Admin dugaaraasaa UP zai awaad ON gej bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 60,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(30),
    updated_at: daysAgo(0),
  },
  {
    id: "item-i61",
    category_id: "cat-upoint",
    title: "Upoint- ийн үлдэгдлээс виртуал дансаа цэнэглэх",
    message: "UP zai awaad DANS zai awaad Tsenegleh dun zai awaad Nuuts kodoo bicheed 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 61,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(29),
    updated_at: daysAgo(1),
  },
  {
    id: "item-i62",
    category_id: "cat-upoint",
    title: "Upoint-ийн үлдэгдлээ шалгах",
    message: "UP gej bicheed 139898 dugaart ilgeene uldegdelee shalgana uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 62,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(28),
    updated_at: daysAgo(2),
  },
  {
    id: "item-i63",
    category_id: "cat-upoint",
    title: "Upoint оноогоор NVOD сувгаас кино захиалах",
    message: "UP zai awaad Suvgiin dugaar /***/ zai awaad kinoni kod /**/ zai awaad nuuts kod /****/ 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 63,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(27),
    updated_at: daysAgo(3),
  },
  {
    id: "item-i64",
    category_id: "cat-upoint",
    title: "Upoint оноогоор RVOD сувгаас кино захиалах",
    message: "UP zai awaad KINO zai awaad kinoni kod zai awaad 4orontoi nuuts kod 139898-d ilgeene uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 64,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(26),
    updated_at: daysAgo(4),
  },
  {
    id: "item-i65",
    category_id: "cat-busad",
    title: "HELP",
    message: "139898 dugaart HELP gej bicheed H1-H4-H2 gesen zamig songon smart kartaa idevhjuulne uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 65,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(25),
    updated_at: daysAgo(0),
  },
  {
    id: "item-i66",
    category_id: "cat-busad",
    title: "IVR",
    message: "Ta sungaltaa hiisnii daraa huleen avagchaa asaalttai uyd Admin dugaaraasaa 1434 dugaart zalgan 1 deer 2 udaa darj kardaa idevhijuulne uu.\nDDISH",
    additional_info: null,
    keywords: null,
    display_order: 66,
    is_popular: false,
    is_active: true,
    created_at: daysAgo(24),
    updated_at: daysAgo(1),
  },
];
